### ISSUE TITLE
How to draw Figure 11

### ISSUE THREAD

**Issue by chenjiachengzzz** [freebeing1/Uniwin#1]
Very great Work. I would like to ask you how to plot the Mean attention distance shown in Figure 11

**Comment by freebeing1** [comment]
Hello!

First of all, thank you very much for your interest in my project. I appreciate your question regarding how to plot the Mean attention distance as shown in Figure 11.

The Mean Attention Distance depicted in Figure 11 was measured in the same manner as introduced in the ViT paper ("An Image is Worth 16x16 Words: Transformers for Image Recognition at Scale"). To implement this, the code was written with reference to the link below.

https://gist.github.com/simonster/155894d48aef2bd36bd2dd8267e62391

Thank you once again for your interest in my project.

**Comment by chenjiachengzzz** [comment]
> Hello!
> 
> First of all, thank you very much for your interest in my project. I appreciate your question regarding how to plot the Mean attention distance as shown in Figure 11.
> 
> The Mean Attention Distance depicted in Figure 11 was measured in the same manner as introduced in the ViT paper ("An Image is Worth 16x16 Words: Transformers for Image Recognition at Scale"). To implement this, the code was written with reference to the link below.
> 
> https://gist.github.com/simonster/155894d48aef2bd36bd2dd8267e62391
> 
> Thank you once again for your interest in my project.

thank you very much! you are well come!
